---
- name: Configure Cisco Devices
  hosts: sandbox-iosxe-latest-1.cisco.com
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Apply configuration commands
      cisco.ios.ios_config:
        commands:
          - 'hostname MyCiscoRouter'

